# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches:
      - 'master'
 
jobs:
  cypress-test:
   name: Run on Chrome 83
   runs-on: ubuntu-18.04
   container: cypress/browsers:node12.18.0-chrome83-ff77
   steps:
     - uses: actions/checkout@v2
     - name: Install a project with a clean slate
       run: |
        npm ci
        $(npm bin)/cypress cache path
        $(npm bin)/cypress cache list
        $(npm bin)/cypress verify
     - name: Run Cypress tests
       run: npm run test:chrome
       continue-on-error: true
     - name: Copy test execution
    
       run: |
        mkdir public
        cp -r cypress/videos public/videos
        cp -r cypress/screenshots public/screenshots
     - name: Merge test report
       run: npm run combine:merge
     - name: Generate HTML report
       run: npm run report:generate
     - name: Deploy report page
       uses: peaceiris/actions-gh-pages@v3
       with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
